export const sampleQuestions = {
  bengali: [
    {
      Question: "কবিগুরু রবীন্দ্রনাথ ঠাকুরের জন্মসাল কত?",
      OptionA: "১৮৬১",
      OptionB: "১৮৬৫",
      OptionC: "১৮৭১",
      OptionD: "১৮৮১",
      CorrectAnswer: "A",
      UserAnswer: "",
    },
    {
      Question: "বাংলা সাহিত্যের প্রথম মহিলা কবি কে?",
      OptionA: "বেগম রোকেয়া",
      OptionB: "কামিনী রায়",
      OptionC: "চন্দ্রাবতী",
      OptionD: "সুফিয়া কামাল",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "‘পদ্মাবতী’ নাটকটির রচয়িতা কে?",
      OptionA: "মাইকেল মধুসূদন দত্ত",
      OptionB: "রবীন্দ্রনাথ ঠাকুর",
      OptionC: "দীনবন্ধু মিত্র",
      OptionD: "মীর মশাররফ হোসেন",
      CorrectAnswer: "D",
      UserAnswer: "",
    },
  ],

  english: [
    {
      Question: "Choose the correct sentence:",
      OptionA: "She don't like apples",
      OptionB: "She doesn't likes apples",
      OptionC: "She doesn't like apples",
      OptionD: "She don't likes apples",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "What is the synonym of 'Happy'?",
      OptionA: "Sad",
      OptionB: "Joyful",
      OptionC: "Angry",
      OptionD: "Tired",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "Which word is a noun?",
      OptionA: "Beautiful",
      OptionB: "Run",
      OptionC: "Happiness",
      OptionD: "Quickly",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
  ],

  science: [
    {
      Question: "What is the chemical symbol for Gold?",
      OptionA: "Go",
      OptionB: "Gd",
      OptionC: "Au",
      OptionD: "Ag",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "Which planet is known as the Red Planet?",
      OptionA: "Venus",
      OptionB: "Mars",
      OptionC: "Jupiter",
      OptionD: "Saturn",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "What is the powerhouse of the cell?",
      OptionA: "Nucleus",
      OptionB: "Mitochondria",
      OptionC: "Ribosome",
      OptionD: "Endoplasmic Reticulum",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
  ],

  math: [
    {
      Question: "What is the value of π (pi) approximately?",
      OptionA: "3.14",
      OptionB: "2.71",
      OptionC: "1.61",
      OptionD: "3.16",
      CorrectAnswer: "A",
      UserAnswer: "",
    },
    {
      Question: "Solve: 2x + 5 = 15",
      OptionA: "x = 5",
      OptionB: "x = 10",
      OptionC: "x = 7.5",
      OptionD: "x = 2.5",
      CorrectAnswer: "A",
      UserAnswer: "",
    },
    {
      Question: "What is the area of a circle with radius 7cm?",
      OptionA: "44 cm²",
      OptionB: "154 cm²",
      OptionC: "49 cm²",
      OptionD: "22 cm²",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
  ],
  computer: [
    {
      Question: "কম্পিউটার শব্দটি কোন ইংরাজী শব্দ থেকে এসেছে?",
      OptionA: "Compact",
      OptionB: "Compute",
      OptionC: "Connect",
      OptionD: "Compare",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "Compute' শব্দটির অর্থ কী?",
      OptionA: "লেখা",
      OptionB: "গণনা",
      OptionC: "যোগাযোগ",
      OptionD: "বিশ্লেষণ",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "কম্পিউটারের একটি উল্লেখযোগ্য বৈশিষ্ট্য কী?",
      OptionA: "তথ্যের ধীর আদান প্রদান",
      OptionB: "বিপুল পরিমাণ তথ্য সংরক্ষণ করা",
      OptionC: "শুধুমাত্র সরল গাণিতিক গণনা করা",
      OptionD: "তথ্যের নিরাপত্তা সুরক্ষিত না করা",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "সবচেয়ে প্রাচীন গণনা করার যন্ত্রের নাম কী?",
      OptionA: "পাস্কালাইন",
      OptionB: "অ্যানালিটিক্যাল ইঞ্জিন",
      OptionC: "অ্যাবাকাস (ABACUS)",
      OptionD: "ডিফারেন্সিয়াল ইঞ্জিন",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "অ্যাবাকাস কত বছর আগে আবিষ্কৃত হয়েছিল?",
      OptionA: "প্রায় এক হাজার বছর",
      OptionB: "প্রায় দুই হাজার বছর",
      OptionC: "প্রায় তিন হাজার বছর",
      OptionD: "প্রায় পাঁচ হাজার বছর",
      CorrectAnswer: "D",
      UserAnswer: "",
    },
    {
      Question: "অ্যাবাকাস কোন দেশের বিজ্ঞানীরা আবিষ্কার করেন?",
      OptionA: "ভারত",
      OptionB: "চীন",
      OptionC: "ইংল্যান্ড",
      OptionD: "আমেরিকা",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "নেপিয়ার্স বোন বা স্লাইড রুল কে আবিষ্কার করেন?",
      OptionA: "চার্লস ব্যাবেজ",
      OptionB: "জন নেপিয়ার (John Nepier)",
      OptionC: "প্যাসকাল",
      OptionD: "ব্লেইজ পাস্কাল",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "পাস্কালাইন নামে একটি নতুন যন্ত্র কে আবিষ্কার করেন?",
      OptionA: "চার্লস ব্যাবেজ",
      OptionB: "জন নেপিয়ার",
      OptionC: "প্যাসকাল",
      OptionD: "নিউটন",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "পাস্কালাইন কত সালে আবিষ্কৃত হয়?",
      OptionA: "১৬১৭ সালে",
      OptionB: "১৮৩৩ সালে",
      OptionC: "১৬৪২ সালে",
      OptionD: "১৮১২ সালে",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "চার্লস ব্যাবেজ কত সালে অ্যানালিটিক্যাল ইঞ্জিন আবিষ্কার করেন?",
      OptionA: "১৬৪২ সালে",
      OptionB: "১৮১২ সালে",
      OptionC: "১৮৩৩ সালে",
      OptionD: "১৬১৭ সালে",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "প্রথম যান্ত্রিক কম্পিউটার নামে কোনটি পরিচিত?",
      OptionA: "পাস্কালাইন",
      OptionB: "ডিফারেন্সিয়াল ইঞ্জিন",
      OptionC: "অ্যাবাকাস",
      OptionD: "অ্যানালিটিক্যাল ইঞ্জিন",
      CorrectAnswer: "D",
      UserAnswer: "",
    },
    {
      Question: "কাকে কম্পিউটারের জনক বলা হয়?",
      OptionA: "জন নেপিয়ার",
      OptionB: "প্যাসকাল",
      OptionC: "চার্লস ব্যাবেজ",
      OptionD: "গটফ্রিড লিবনিজ",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "The Mill নামে অ্যানালিটিক্যাল ইঞ্জিনের কোন অংশটি পরিচিত ছিল?",
      OptionA: "স্টোর (Store)",
      OptionB: "এরিথমেটিক ইউনিট (Arithmatic Unit)",
      OptionC: "কন্ট্রোল ইউনিট (Control Unit)",
      OptionD: "ইনপুট ডিভাইস (Input Device)",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "অ্যানালগ কম্পিউটার কোথায় ব্যবহৃত হয়?",
      OptionA: "শিক্ষা প্রতিষ্ঠানে",
      OptionB: "আবহাওয়া দপ্তরে",
      OptionC: "ব্যাঙ্কে",
      OptionD: "গবেষণার কাজে",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "ডিজিটাল সিগন্যাল কী দ্বারা গঠিত হয়?",
      OptionA: "শুধু ০ দ্বারা",
      OptionB: "শুধু ১ দ্বারা",
      OptionC: "০ ও ১ দ্বারা",
      OptionD: "০ থেকে ৯ পর্যন্ত সংখ্যা দ্বারা",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "০ ও ১ কে কম্পিউটারের পরিভাষায় কী বলে?",
      OptionA: "ডেসিমাল সংখ্যা",
      OptionB: "বাইনারি সংখ্যা (Binary Number)",
      OptionC: "গাণিতিক সংখ্যা",
      OptionD: "কোড সংখ্যা",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "হাইব্রিড কম্পিউটারে কোন কম্পিউটারের নির্ভুলতা পাওয়া যায়?",
      OptionA: "অ্যানালগ কম্পিউটার",
      OptionB: "ডিজিটাল কম্পিউটার",
      OptionC: "সুপার কম্পিউটার",
      OptionD: "মেনফ্রেম কম্পিউটার",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "কোন কম্পিউটারকে পার্সোনাল কম্পিউটারও বলা হয়?",
      OptionA: "সুপার কম্পিউটার",
      OptionB: "মেনফ্রেম কম্পিউটার",
      OptionC: "মিনি কম্পিউটার",
      OptionD: "মাইক্রো কম্পিউটার",
      CorrectAnswer: "D",
      UserAnswer: "",
    },
    {
      Question: "কোন কম্পিউটারকে ডেস্কটপ কম্পিউটারও বলা হয়?",
      OptionA: "মিনি কম্পিউটার",
      OptionB: "ল্যাপটপ কম্পিউটার",
      OptionC: "পার্সোনাল কম্পিউটার",
      OptionD: "সুপার কম্পিউটার",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "আবহাওয়ার পূর্বাভাস দেওয়ার কাজে কোন কম্পিউটার ব্যবহৃত হয়?",
      OptionA: "হাইব্রিড কম্পিউটার",
      OptionB: "সুপার কম্পিউটার",
      OptionC: "ডেস্কটপ কম্পিউটার",
      OptionD: "মিনি কম্পিউটার",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "কম্পিউটারের কাজ করার গতির ক্ষেত্রে কোনটি সত্য?",
      OptionA: "অত্যন্ত ধীর গতি সম্পন্ন",
      OptionB: "মাঝারি গতি সম্পন্ন",
      OptionC: "অত্যন্ত দ্রুত গতি সম্পন্ন",
      OptionD: "দ্রুত গতির নয়",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "ই-কমার্স (E-commerce) বলতে কী বোঝায়?",
      OptionA: "ই-মেইল পরিষেবা",
      OptionB: "কম্পিউটারের মাধ্যমে পণ্যের ক্রয় বিক্রয়",
      OptionC: "ইন্টারনেট ব্যবহার করে যোগাযোগ",
      OptionD: "ব্যাঙ্কের লেনদেন",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question: "অ্যানালিটিক্যাল ইঞ্জিনের ইনপুট ডিভাইস হিসেবে কী ব্যবহৃত হতো?",
      OptionA: "পাঞ্চ কার্ড",
      OptionB: "প্রিন্টিং মেশিন",
      OptionC: "মাউস",
      OptionD: "কি-বোর্ড",
      CorrectAnswer: "A",
      UserAnswer: "",
    },
    {
      Question:
        "ল্যাপটপ কম্পিউটার কী দ্বারা চালিত হয়, যার জন্য এটিকে যেকোনো স্থানে নিয়ে যাওয়া যায়?",
      OptionA: "এ.সি. পাওয়ার",
      OptionB: "ব্যাটারি",
      OptionC: "মেনফ্রেম",
      OptionD: "জেনারেটর",
      CorrectAnswer: "B",
      UserAnswer: "",
    },
    {
      Question:
        "একটি সুপার কম্পিউটার সাধারণত সেকেন্ডে কত বা তার বেশী সংখ্যক গণনা করতে সক্ষম?",
      OptionA: "দশ লক্ষ",
      OptionB: "এক কোটি",
      OptionC: "দশ হাজার কোটি",
      OptionD: "এক হাজার কোটি",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "মেনফ্রেম কম্পিউটার সাধারণত কোথায় ব্যবহৃত হয়?",
      OptionA: "ছোট অফিস বা স্কুল",
      OptionB: "আবহাওয়া দপ্তর",
      OptionC: "বড় বড় প্রতিষ্ঠান যেমন ব্যাঙ্ক, রেল পরিষেবা",
      OptionD: "ব্যক্তিগত ব্যবহার",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "ডিফারেন্সিয়াল ইঞ্জিন কে আবিষ্কার করেন?",
      OptionA: "জন নেপিয়ার",
      OptionB: "প্যাসকাল",
      OptionC: "চার্লস ব্যাবেজ",
      OptionD: "জোহান রেইটার",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question:
        "কোন প্রকার কম্পিউটারে অ্যানালগ কম্পিউটারের কাজের গতি এবং ডিজিটাল কম্পিউটারের নির্ভুলতা উভয়ই পাওয়া যায়?",
      OptionA: "সুপার কম্পিউটার",
      OptionB: "মিনি কম্পিউটার",
      OptionC: "হাইব্রিড কম্পিউটার",
      OptionD: "মেনফ্রেম কম্পিউটার",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question:
        "অ্যানালিটিক্যাল ইঞ্জিনের কোন অংশটি গণনা কার্যের ফলাফল সংগ্রহ করে রাখত?",
      OptionA: "দি মিল",
      OptionB: "কন্ট্রোল ইউনিট",
      OptionC: "স্টোর (Store)",
      OptionD: "আউটপুট ডিভাইস",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
    {
      Question: "মাইক্রো কম্পিউটারগুলিকে সাধারণত কত ভাগে ভাগ করা যায়?",
      OptionA: "তিন প্রকার",
      OptionB: "চার প্রকার",
      OptionC: "দুই প্রকার",
      OptionD: "পাঁচ প্রকার",
      CorrectAnswer: "C",
      UserAnswer: "",
    },
  ],
};

export const getSampleQuestions = (subject) => {
  return sampleQuestions[subject] || sampleQuestions.english;
};
